# Generated by Django 3.2.6 on 2021-09-02 22:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='task',
            options={'ordering': ['-date_created']},
        ),
        migrations.AddField(
            model_name='task',
            name='date_created',
            field=models.DateField(auto_now_add=True, null=True),
        ),
    ]
